### ISSUE TITLE
Examples gulp

### ISSUE THREAD

**Issue by nicothin** [webschik/postcss-less#8]
I created a [test repository](https://github.com/nicothin/stylelint-less-test) (gulp), and when I get a simple analysis of the paradoxical error.
```
[22:31:07] Starting 'lint:less'...
[22:31:07] 'lint:less' errored after 28 ms
[22:31:07] Error in plugin 'gulp-postcss'
Message:
    D:\projects\stylelint-less-test\style.less:3:21: Missed semicolon
blockquote {
  border: 1px solid #999 !important;
                    ^
  page-break-inside: avoid;
```
Please tell me what I'm doing wrong?

**Comment by webschik** [comment]
Hi!

You have this problem because `postcss-less` isn't integrated to `Stylelint` (discussion about it https://github.com/stylelint/stylelint/issues/810)

When Stylelint will support this parser you be able to include it in the next way:

````js         
        .pipe(postcss([
            stylelint({
                "syntax": "less", //now Stylelint is supporting 'scss' value
                "rules": {
                    "color-no-invalid-hex": true,
                    "max-empty-lines": 2,
                    "indentation": ["tab", {
                        "except": ["value"]
                    }]
                }
            }),
            reporter({clearMessages: true})
        ]));
````


I use Stylelint with configuration  "syntax": "less", but I had to patch its source files.
